### ISSUE TITLE
LDAP + Mongo

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#100]
Couple of questions for @Mctalian 
* Does LDAP access work outside the Rockwell network?
* What do I put in the ldapAuth.js file? (Did you send an email out Friday because I wouldn't have seen that, I was off Friday).

**Comment by Mctalian** [comment]
No and yes, respectively. We'll need a development only account for outside
Rockwell.

I can go into more detail when I'm back in Cleveland

**Comment by YashdalfTheGray** [comment]
Well that was easy. Sounds good, I was thinking of mocking that out for external testing which is all I seem to be able to do. I also don't know if we can even mock something like that.

**Comment by Mctalian** [comment]
I have an idea, I'll explain when I'm at a computer

**Comment by YashdalfTheGray** [comment]
Word.

Yash Kulshrestha
yash.kulshrestha@gmail.com
(614)563-1153

**Comment by Mctalian** [comment]
My idea is having something server side that leverages `process.env.NODE_ENV = 'development';`

Something like

```
app.post('/login', function(req, res, next) {
    if (process.env.NODE_ENV === 'development') {
        // check for a hard-coded username, perhaps we have 2 so we can test author and non-author
        // password could just not matter.
    }
    else {
        // LDAP
    }
}
```

Not really anything fancy, and we could probably get more sophisticated, but this way will work and should remove the need for people to be connected to the RA network to test things.

**Comment by Mctalian** [comment]
Once we do all this and restructure the DB, we'll have to generate new test data, something that has at least 2 ideas, one for each user so we can test author/non-author capabilities. It's about time to get rid of the old Innovation Challenge ideas.

**Comment by Mctalian** [comment]
Is this good to close Yash?

**Comment by YashdalfTheGray** [comment]
Yup.
