### ISSUE TITLE
Login "screen"

### ISSUE THREAD

**Issue by monotkate** [YashdalfTheGray/flintandsteel#105]
When you click to login it's using a form that looks like it's designed to be a drop down, but isn't a drop down.  Almost the entire page ends up white and empty with the tiny white login box and it looks disjointed.  Possible solution is to have as a drop down that overlays main page, or to tweak the design to look better on a full page.

**Comment by Mctalian** [comment]
That's a good point. I've thought about this myself. I'm thinking we're
going to do most of the UX improvements after we've got a lot of the main
functionality done. Unless you want to give it a shot yourself, I like the
drop down or modal pattern.

**Comment by monotkate** [comment]
If I've got some time I'll poke around at it
