### ISSUE TITLE
Dev environment shouldn't need secrets\ldapAuth

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#112]
This file should only be required for PROD

**Comment by YashdalfTheGray** [comment]
Check out my comment in PR #110 about this. I don't think there is a way to do this that doesn't require a lot of extra code. I think the file should be required globally, the contents of the file shouldn't matter for dev but they should matter for prod.

**Comment by Mctalian** [comment]
I'll look into it later.

**Comment by Mctalian** [comment]
PR #122
