### ISSUE TITLE
Post mongodb cleanup task

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#113]
Creating this to keep track of all the clean up required to finish mongo implementation. Some cleanup tasks - 
* Changes to `README.md`
* API changes to `loginSvc` and `ideaSvc` and related mocks

I'll add others as I think of them. Pulling in @Mctalian into this too.

**Comment by Mctalian** [comment]
Not sure how many of these I covered in my commits. We'll have to list out the detailed cleanup at some point.

**Comment by YashdalfTheGray** [comment]
Yeah, we'll have to systematically go through the app and make sure everything works. But at least development is not blocked now.

**Comment by Mctalian** [comment]
I think I covered the cleanup with PR #131 and everything in the app should now work. We still aren't adhering to the schema, so that's something we'll still have to do.

**Comment by YashdalfTheGray** [comment]
Yeah, we can look at cleaning that up.

**Comment by YashdalfTheGray** [comment]
@Mctalian can we close this since the DB is pretty much implemented and cleaned up?

**Comment by Mctalian** [comment]
Yeah, that should be fine. I'll track the actual implementation of the rest of the schema in one of the trello cards.

**Comment by YashdalfTheGray** [comment]
Sounds good.
