### ISSUE TITLE
Sidebar should show a message if there are no ideas

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#124]
It shows 5 blank idea headers. We need to make this fail gracefully, perhaps even show a message "There are no ideas, create your own now!" Or something cheesy like that.

**Comment by LongArmMcGee** [comment]
Did you add a trello card? this sounds like an easy fix for me or braun to
do

**Comment by Mctalian** [comment]
Seems more like a bug than a feature, so I raised an issue not a trello card. We can put a card up if you prefer.

**Comment by LongArmMcGee** [comment]
whatever, so long as it's recorded for someone to address.

**Comment by Mctalian** [comment]
PR #145 fixed the actual issue, but it still should show a message if there are no ideas. I will move this to a trello card later and close the issue.

**Comment by YashdalfTheGray** [comment]
Can we close this issue?

**Comment by Mctalian** [comment]
No, nothing has been done to fix it

**Comment by Mctalian** [comment]
I'm thinking something like this when we have no ideas (except much better, I just altered HTML in Chrome Inspector):

![image](https://cloud.githubusercontent.com/assets/5081281/11321321/6ccf6e42-9087-11e5-8c45-4a5c1445854d.png)

**Comment by davethenipper** [comment]
Bob and I talked.  This will be phase two since we have a workaround and its not a blocker.

**Comment by YashdalfTheGray** [comment]
Alright, so can we close this issue and create a card?

**Comment by Mctalian** [comment]
@davethenipper create a card on the new board and close this por favor

**Comment by davethenipper** [comment]
Done
