### ISSUE TITLE
Nodemon is watching the DB!!!

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#126]
Anytime a write occurs to the DB, the server restarts. No bueno. It's a simple fix, and I did so on the production server as a stop gap, but we'll need to throw an official PR up.

In case anyone wants to take care of it, you change `'spec/*'` in the `'ignore'` field to `'server\datastore\*'` for both Prod and Dev starts. It should look like the following.

```
gulp.task('start:dev', ['_cleanUp', 'test:client', 'inject'], function() {
    "use strict";

    nodemon({
        script: 'server/server.js',
        env: { 'NODE_ENV': 'development' },
        'ignore': ['server/datastore/*']
    });
});

gulp.task('start:prod', ['_cleanUp', 'test:client', 'inject'], function() {
    "use strict";

    nodemon({
        script: 'server/server.js',
        env: { 'NODE_ENV': 'production' },
        'ignore': ['server/datastore/*']
    });
});
```

**Comment by LongArmMcGee** [comment]
You could have made the change in the time it took you to write this email!

**Comment by Mctalian** [comment]
A) I knew you'd say that.
B) Same could be said about you!

**Comment by Mctalian** [comment]
I'll get it right now.
