### ISSUE TITLE
Standard SSL cert details

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#132]
@Mctalian 

We might need to leave standard SSL cert details that everyone should use when generating and signing their certs. I know it doesn't matter a whole lot since development environment but it would be nice to be on the same page. 

What do you think?

**Comment by Mctalian** [comment]
I agree, was going to handle that later. Development environment was higher
priority. I'll have to go over self signing a cert again to be able to do a
write up on it.

**Comment by YashdalfTheGray** [comment]
Yeah, that's how I would have done it. And to be honest, we could keep a card in trello with all the details so that you wouldn't have to write something up about it. When someone asks, point them to the trello card and tell them to use the tool. Since this is development thing and the entire team has access to the trello thing, it doesn't have to be written up formally.

**Comment by Mctalian** [comment]
I put something up on a new board in Trello.
