### ISSUE TITLE
Should toast the user if they navigate to the addIdea page via the URL without logging in

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#138]
If a user types <hostname>/addIdea and they are not logged in, it will redirect them to the "home" state (pending PR #137). We should toast them notifying them that they need to login before posting a new idea.

Oh and this toast should have an OK button!

**Comment by YashdalfTheGray** [comment]
I can also handle this as I'll be working on the toast thing anyway.
