### ISSUE TITLE
All toasts should have OK's, especially if they cover functionality.

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#139]
I got so annoyed with the toasts way back when we were testing login that I added an OK to the "login" toast. Now when we're quickly logging in and out of accounts, the "logout" toast gets in the way.

I propose a toast :laughing: that all existing toasts and future toasts have a way to dismiss them!

Who's with me?!

**Comment by davethenipper** [comment]
I'll toast to that.

**Comment by alanlgirard** [comment]
Cheers to that!  I got annoyed and added an OK to the logout toast on my branch

**Comment by YashdalfTheGray** [comment]
Is there a card for this? This is something that I've been thinking about for a while so I can work on this. It's simple enough.

**Comment by monotkate** [comment]
I've got that set to go in for the logout with my quick enter button fix.  It should be submitted this morning if I can get it done before my lunch meeting

**Comment by YashdalfTheGray** [comment]
For all toasts? Because I was thinking of revamping how the toasting happens in the application. There is a lot WET code when it comes to toasting and I have a service that I can pull from one of my other applications and make it DRY.

**Comment by Mctalian** [comment]
@monotkate 's PR just has the existing Logout toast have an "OK". The Login toast has an "OK" already. Not sure how many other toasts we're planning on having. I know there's an "Idea was deleted" toast and an "Idea no longer exists" toast. Both of which (I think) have "OK" buttons. I'm pretty positive they've all be copied and pasted around the code.

If you'd like to make it DRYer feel free to put a card up, or duplicate this issue as a card in Trello. Whatever you feel is a good use of your time is fine with me!

**Comment by YashdalfTheGray** [comment]
Closed in PR #144.
