### ISSUE TITLE
Node 4.1

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#150]
Alright, so I've been running node 4 for a couple of weeks locally on my side and I haven't had any issues with it so far. I also just updated the travis build on the `master-author` branch to node 4.1 and it passed too. 

I think it's time to update to Node 4.1 folks. 

I know that @bcbrennecke has been running node 4 for a few weeks too. What are your thoughts? As far as I'm concerned, it's about as stable as we're going to get. 

Other thoughts, @Mctalian, @davethenipper?

**Comment by Mctalian** [comment]
I've been running at least 0.12.x on most of my machines. Just upgraded to
5.0.0 yesterday. I can check to see if it works with our stuff. I'm pretty
sure it does.

**Comment by davethenipper** [comment]
I have no other thoughts, I leave this in your guys competent hands.

**Comment by davethenipper** [comment]
Thought: Maybe a 4.1 vs. 5 comparison?

**Comment by Mctalian** [comment]
At this moment in time, v4.2.2 is the latest LTS (Long Term Support) version and v5.1.0 is the latest Stable version. I personally think we should only upgrade to LTS versions. That's what ESW does for Jenkins.

**Comment by YashdalfTheGray** [comment]
Yeah, I would agree with only upgrading to LTS releases. Travis is yet to have 4.2.2 but I'm sure they're working on that. I would really like to at least update to 4.1 so that we can get around some of the node-gyp issues and sudo issues on macs. They're not a large concern but they have stopped development long enough for me to want to upgrade the project to node 4.1 at the very least. 

This doesn't change a lot in the project itself but we're going to have to get everyone to upgrade before they check stuff in. We can even talk about `nvm` and `nvmw` if you really want to keep the old node versions around for whatever reason.

**Comment by Mctalian** [comment]
I don't particularly see a need for that. Let's keep it simple.

**Comment by Mctalian** [comment]
Wait... node-gyp issues... aren't those an optional dependency? I see those on Windows and everything still works just fine. It shows errors, but since it's an optional dependency, I ignore them. The only reason you wouldn't see those errors in something like Node 5 (can't speak for Node 4 right now) is because I think they dropped support of optional dependencies... I hope this isn't the node-gyp issue you were referring to because you weren't *actually blocked by it, then.

**Comment by YashdalfTheGray** [comment]
I wasn't blocked but I'd rather not have build errors at all. Because then it becomes hard to figure out what is an actual error and what isn't.

**Comment by Mctalian** [comment]
:100: True dat. I was just making sure we haven't been "Yash-less" for the wrong reason s! :stuck_out_tongue_closed_eyes:

**Comment by Mctalian** [comment]
With that being said, I'm still getting those errors on 4.2.2

**Comment by Mctalian** [comment]
And also on 5.1.0... I must have something on my work computers that I don't have on my home rig...

Not sure if we'll be able to satisfy these optional dependency errors unless everyone goes and installs what it's asking for.

**Comment by YashdalfTheGray** [comment]
Huh, that's weird, ever since on 5.1.1, I haven't gotten issues with npm install on our repo. I also want us to use the post-io.js version of node, the io.js merge brought along a TON of performance fixes and tweaks.

**Comment by YashdalfTheGray** [comment]
Alright, so everyone okay with upgrading to node 4.2.2?

**Comment by YashdalfTheGray** [comment]
PR #159 closes this.
