### ISSUE TITLE
Length of idea title

### ISSUE THREAD

**Issue by bcbrennecke** [YashdalfTheGray/flintandsteel#153]
I can create an idea with no title.  Then when you delete it it is deleting "null".

**Comment by Mctalian** [comment]
Look into:
[Angular Input Parameters like ng-minlength](https://docs.angularjs.org/api/ng/input/input%5Btext%5D)
[Angular Material Input Parameters like md-maxlength](https://material.angularjs.org/latest/api/directive/mdInput)

Ultimately we need to start adding "required" fields to our forms. It will knock out a lot of issues like this.

**Comment by alanlgirard** [comment]
Closed with PR #197
