### ISSUE TITLE
Campfire API Integration

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#154]
[Call Kenny Loggins, we need more Danger Zone!!!!!!!](https://www.youtube.com/watch?v=yK0P1Bk8Cx4)

**Comment by davethenipper** [comment]
High Priority

**Comment by YashdalfTheGray** [comment]
Are we serious about campfire?

**Comment by Mctalian** [comment]
I just want to /play things

**Comment by Mctalian** [comment]
So after looking at what Campfire is, no. Probably not serious.

**Comment by YashdalfTheGray** [comment]
Explain the /play thing to me...think I'm missing some context here.

**Comment by Mctalian** [comment]
http://www.emoji-cheat-sheet.com/ scroll down to the bottom

**Comment by YashdalfTheGray** [comment]
Oh that's awesome. There is [a cost](https://campfirenow.com/signup) involved though. @davethenipper do you think we have a business case for danger zone?

**Comment by davethenipper** [comment]
I would imagine this i a business case.  Probably the perfect time to try out how to use this budget thing.

**Comment by YashdalfTheGray** [comment]
:smile:

**Comment by Mctalian** [comment]
I think we should close this, unfortunately.

**Comment by davethenipper** [comment]
Probably, no point in making more work for ourselves...

**Comment by Mctalian** [comment]
#Test

**Comment by Mctalian** [comment]
# Test
