### ISSUE TITLE
Idea score

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#16]
Likes + manager likes + types of backs (experience, funding, knowledge)

**Comment by Mctalian** [comment]
Another element of scoring could be "Reporting" or "Flagging" an idea as inappropriate.

Reporting and Flagging should be in the overflow section, next to the account button.

Have radio buttons that force users to choose a Violation of Company Policy. If enough matching complaints come through, blacklist the idea/comment.

**Comment by YashdalfTheGray** [comment]
I'm going to close this since I think we're kind of past thinking about what this was going to be but kind of not there yet of what this can mean for the way that we have structured data right now.
