### ISSUE TITLE
Multiple backs

### ISSUE THREAD

**Issue by monotkate** [YashdalfTheGray/flintandsteel#161]
I was messing around with some stuff and noticed that if you back an idea there is nothing to prevent you from backing a second time. If you do back twice that makes you show up in the team selection window twice. Guessing this isn't expected behavior.

**Comment by Mctalian** [comment]
There's a PR open to address this, actually :) David T put it up on Friday

**Comment by monotkate** [comment]
Perfect.  That's what I get for doing half my coding on planes.  Can't check issues.

**Comment by Mctalian** [comment]
PR #156 should address this just fine.

**Comment by Mctalian** [comment]
PR #156 was merged. Closing.
