### ISSUE TITLE
Multiple Back Types Possible When Editing

### ISSUE THREAD

**Issue by Daviddt17** [YashdalfTheGray/flintandsteel#165]
When editing a back, the types loaded into the chip model are not included in the duplicate check. I could not find a fix for this, so it may be worth considering a different setup for choosing back types.

Maybe a checkbox list or a slide toggle list?

**Comment by Daviddt17** [comment]
[PR 156](https://github.com/YashdalfTheGray/flintandsteel/pull/156) for reference.

**Comment by LongArmMcGee** [comment]
Weren't we talking about having a 'popup' window to solve this?

**Comment by Mctalian** [comment]
Yes that's what his last sentence is referring to as we discussed in
today's meetings.

**Comment by LongArmMcGee** [comment]
Ya gotta spell it out for me

**Comment by alanlgirard** [comment]
Closed by @monotkate PR 188
