### ISSUE TITLE
Long Text in Comments, Backers, Updates eventually get truncated

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#166]
We should probably leave people with a text area for typing and text-wrapping for viewing a comment because people like to type a lot. For instance, if this text was on our site, I'm pretty certain, to the 99.9% confidence interval, that the text would be truncated when viewing it in the comments, backs, or updates view. I think we should allow our users the ability to type their little hearts out in the event that they have a lot to say, even if what they say doesn't seem to add any value. It is like the age old Zen saying on attachement: "The tighter you squeeze, the less you have." Ipso facto, we need to allow for longer comments, backs, and statuses without truncating them.

**Comment by alanlgirard** [comment]
Maybe implement a "see more..." link at the end of long comments etc like Facebook does to allow the site to not become too cluttered, but I approve of allowing the user to not be limited.

**Comment by Daviddt17** [comment]
We should also word wrap on input for updates and comments. As of now it's a single line.

**Comment by Daviddt17** [comment]
Also, the press enter to submit comment feature will have to be deleted or done in some other way. The user needs a way to enter newlines.

**Comment by Mctalian** [comment]
Good point. Maybe we can use "shift+enter" to post a comment. Or some other
modifier key.

**Comment by Daviddt17** [comment]
"shift-enter" sounds perfect.

**Comment by YashdalfTheGray** [comment]
Change the `<input>` tag inside the `<ng-input-container>` tag to a `<text-area>` tag to resolve this. Make sure to put some kind of a word limit on it too.

**Comment by Mctalian** [comment]
@alanlgirard mentioned he was planning on working on this soon/next in the standup. Feel free to unassign yourself if I misunderstood.

**Comment by alanlgirard** [comment]
Closed with PR #221
