### ISSUE TITLE
Description character limit not checked when submitting idea

### ISSUE THREAD

**Issue by davethenipper** [YashdalfTheGray/flintandsteel#175]
When the character limit for a description is exceeded and the idea is added, the idea gets created with a blank description.

**Comment by YashdalfTheGray** [comment]
This behavior is intended, the bug is that we don't check for valid description text when we create an idea.

**Comment by YashdalfTheGray** [comment]
Updated the bug header and description.

**Comment by alanlgirard** [comment]
Closed with PR #197
