### ISSUE TITLE
You Can Attempt a Login with Blank Username/Password

### ISSUE THREAD

**Issue by davethenipper** [YashdalfTheGray/flintandsteel#176]
Users are able to attempt to login with a blank username/password.

Discussion has been: Don't allow them and use an X?

**Comment by YashdalfTheGray** [comment]
Attempt but it's not successful, yes? When I worked on login, you could try it with blanks and it would just say that those fields are required. 

If this is still true, then it is the intended behavior, no need to worry about it.

**Comment by Mctalian** [comment]
We have a lot of issues with form validation (hence the description issue).
I am of the camp that if something is required, don't even let them submit
while it's blank. Disable the button. I think Login should work this way as
well.

**Comment by YashdalfTheGray** [comment]
We can disable the login button, sure or we can use the `ng-required` and the `<ng-messages>` directive to make sure that we give user feedback on crappy input and the disabling button logic comes built in. They could sit there and click the button all day and nothing would happen provided that all of this sits inside a `<form></form` element.

**Comment by Mctalian** [comment]
I don't think disabling button logic comes for free. I've always had to utilize `ng-disable` and watch for the form to be `$valid` or whatever. I could have been doing it wrong, but I don't want us to make an assumption that something might come for free, if it might not. To be confirmed.

**Comment by YashdalfTheGray** [comment]
That's a good way to do it. If you use `ng-required` and watch for the `$changed` event and see if it's valid. Form validation comes for free if you use `ng-required` and the `<ng-messages>` directives. It will let you click the button but won't run anything because of the `ng-required` checks not passing.

**Comment by alanlgirard** [comment]
Closed with PR #197
