### ISSUE TITLE
Cannot Remove Backing Type

### ISSUE THREAD

**Issue by davethenipper** [YashdalfTheGray/flintandsteel#180]
A user cannot remove their back.  Maybe they don't want to support the idea anymore.

**Comment by Mctalian** [comment]
#202 enabled some work on this. @monotkate has a few more things to do and we can close this one down as well.

**Comment by Mctalian** [comment]
@monotkate , #205 closes this, correct?

**Comment by monotkate** [comment]
👍🏻
