### ISSUE TITLE
Forced To Type To See Backing List

### ISSUE THREAD

**Issue by davethenipper** [YashdalfTheGray/flintandsteel#182]
Forcing a user to start typing to see the backing list leaves them confused.  

Discussion: Have a list of backs automatically pop up that the user can check off.

**Comment by Mctalian** [comment]
May be addressed in @monotkate 's current story depending on how she
chooses to proceed with it.

**Comment by monotkate** [comment]
Addressing this. I got a new backing dialog setup today. Still working on edit right now.

**Comment by alanlgirard** [comment]
Closed with @monotkate PR 188
