### ISSUE TITLE
Logging In Is Not Intuitive

### ISSUE THREAD

**Issue by davethenipper** [YashdalfTheGray/flintandsteel#183]
Some users may not know they need to log in to do things on the website.

Discussion: Grey out areas for those who have not logged in instead of hiding them.  Then make clicking these take them to the login page.  A good example is the create idea button.

**Comment by monotkate** [comment]
I'm adding tooltips right now which should help with some. I think it also tells you to login to comment now. Unless I didn't end up adding it last time. Can we add something on the homepage to get users to login?

**Comment by Daviddt17** [comment]
Yep, I second the login on the homepage. Even better, let's get rid of the default person icon when no one is logged in and replace it with a nice and shiny login button.

**Comment by Daviddt17** [comment]
For instance, I think this:
![signin](https://cloud.githubusercontent.com/assets/5295379/11534727/2bd9e66a-98de-11e5-9802-e85dd86bf038.JPG)

Looks much better than this:
![personsignin](https://cloud.githubusercontent.com/assets/5295379/11534728/2e60db1e-98de-11e5-8d77-5e5f19765916.JPG)

It's way more obvious that it's a sing in button that way.

**Comment by Mctalian** [comment]
I also think we can be a bit more "modern" with our homepage. I can provide
some examples later.

**Comment by YashdalfTheGray** [comment]
@Daviddt17 that sign in button is against the material design guidelines. We can have text but not the red background. Also, Miranda is adding tooltips that should help. All apps should invite people to click around, they learn by doing, telling the user exactly what to do is bad app design. 

That being said, I agree that the person icon isn't intuitive and we should change it to a sign in button but it can't have the `md-raised` class.

**Comment by monotkate** [comment]
Adding the words "Login" on my next PR as soon as I get tests written.  This should make it foolproofingly clear.  It also does not look like shit. :+1:
