### ISSUE TITLE
Something About Liking vs. Backing

### ISSUE THREAD

**Issue by davethenipper** [YashdalfTheGray/flintandsteel#184]
Give an explanation of the difference between a like and a back.

Discussion: if not logged in: "login to comment and leave feedback on this idea."  

The user is logged in but has not backed yet: "Explain Backing here."

**Comment by Mctalian** [comment]
@YashdalfTheGray also mentioned an FAQ as some additional guidance.

**Comment by Mctalian** [comment]
Pretty sure @bcbrennecke's front page redesign will include some guidance on this. Feel free to unassign yourself if I'm incorrect.

**Comment by Mctalian** [comment]
Closed in @bcbrennecke's most recent PR #192
