### ISSUE TITLE
Comments Always Display Current Time

### ISSUE THREAD

**Issue by davethenipper** [YashdalfTheGray/flintandsteel#193]
In the Comments tab of an idea a Comment should display when it was submitted.  Instead it always displays the current time.

**Comment by Mctalian** [comment]
This is visible on [production](https://innovate.ra.rockwell.com/#/idea/5661fc9f044114741b1f2808) on the comments tab FYI

**Comment by monotkate** [comment]
I thought we fixed that a while back? @algirard

**Comment by davethenipper** [comment]
It could be fixed on the most recent stuff.  I'll check it out

**Comment by Mctalian** [comment]
Yeah I hoped that was the case. That's why I mentioned production.

**Comment by monotkate** [comment]
yeah, it's broken.  Let me fix it, I'll submit a pull for it today. I know what's wrong

**Comment by Mctalian** [comment]
Is it because `comment.time` is undefined (so it's momentizing an undefined date which defaults to now) and should be `comment.timeCreated` instead?

**Comment by monotkate** [comment]
Pretty sure that it.  Go ahead and fix it if you can.  In a post donating blood pre cookie hypogylcemic haze I just royally screwed up my files.  Good times.

**Comment by Mctalian** [comment]
First one to assign this issue to themselves gets to fix it! I had to finish job stuff :(

**Comment by Mctalian** [comment]
I'll have a PR up shortly.

**Comment by YashdalfTheGray** [comment]
This change is already on master, it's a long story. This issue should have
been updated.

Yash Kulshrestha
yash.kulshrestha@gmail.com
(614)563-1163

**Comment by Mctalian** [comment]
Got it, I just realized this myself. All good!

**Comment by Mctalian** [comment]
Closed via commit 66300f0df000bf44880921bd2ead0f45721c385d @monotkate can you confirm? Looks like it, locally at least.

**Comment by monotkate** [comment]
yeah, I fixed it.  Like Yash said, long story on the commit.
