### ISSUE TITLE
Bad merge, update deleting

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#194]
335f0872a7ec25a4e2626e9731777d74de6b6e02

There may be more in this merge that I missed. We are using $index based deleting now instead of just passing in the object that we want to delete. It gets confusing if we sort the info in a different way, so it's better to just pass in what we want to delete, not its potentially changing position.

**Comment by YashdalfTheGray** [comment]
So what's this issue about?

**Comment by monotkate** [comment]
I think that's actually the only part that uses index.  I can take ownership and fix it once I get my fork fixed.

**Comment by Mctalian** [comment]
Or I can do it. I'm the one that botched the merge.

If you want though, just assign it to yourself. All we have to do is use
IsUserAuthorOfInteraction or whatever, the generic functions, not the named
ones, then delete the unused code.

**Comment by Mctalian** [comment]
Check out [this diff](https://github.com/YashdalfTheGray/flintandsteel/commit/335f0872a7ec25a4e2626e9731777d74de6b6e02#diff-8209bb1d2129ac6eb03d3627b67711e7R98) for more info on what the issue is, I'm failing to find a more concise way to explain it than what I typed in the issue description above.

**Comment by Mctalian** [comment]
I have time, I'll do it now. Sorry for the email spam!
