### ISSUE TITLE
Someone broke hasUserBacked()

### ISSUE THREAD

**Issue by monotkate** [YashdalfTheGray/flintandsteel#199]
Not the biggest deal, but in the past hasUserBacked() returned `true` for the idea owner as well as the regular backers.  As of this morning (something was changed in the last night time frame because I rebased yesterday afternoon and it still worked), it no longer returns true for the idea owner, but it does for anyone else.  If this is intended, I can easily change the backing code to work with it, but I want to know if it's intended and why it changed.  @YashdalfTheGray @Mctalian was this either of you? @alanlgirard caught it.

**Comment by Mctalian** [comment]
If I did, it wasn't intentional. Looking through my most recent commits that might have affected it, I did not touch that method. If it was within the past 12 or so hours, I'll take a look at the most recent commits.

**Comment by Mctalian** [comment]
Hit the wrong button

**Comment by monotkate** [comment]
wait, I think I accidentally tested the wrong login.  Nvm, still working for me.  If it's still working for you Bob then it's @alanlgirard's own problem not an issue.  Sorry.

**Comment by monotkate** [comment]
I do apparently accidentally delete the owner chip if they edit their backing though, which is a bug I will fix.

**Comment by Mctalian** [comment]
Yeah... I noticed that before. I was going to hold off on that one until we figure out what we want to do with the "Owner" chip... perhaps "Roles Required" will change the way backing types work? Not sure. If you can figure out a simple way to "fix it" then go for it, otherwise, please log an issue.

**Comment by Mctalian** [comment]
I'd keep this one open until we are completely certain that it's not an issue. I see nothing *in the code* that would lead me to believe something broke, but I'd like someone to verify that this is no longer an issue OR post a step by step of how to reproduce it. I'd rather be safe than sorry.

**Comment by monotkate** [comment]
yeah, I'm leaving it open.  I think there's something weird on a new idea with the owner.  Investigating today.  Kids are testing today, and then my afternoon is open.  I'll poke around and see if there's an issue and if I can fix it.

**Comment by alanlgirard** [comment]
Editing the owners backs works for the generated ideas but not for added ideas.

**Comment by Mctalian** [comment]
That's... weird... can't imagine why those things would be different... hmmm

**Comment by monotkate** [comment]
I'm digging through the database right now trying to figure out what's going on.  It seems to send the edit properly to ideaSvc, but when it refreshes the idea it doesn't retain it.  I'm struggling to get it to tell me what it's putting into the database with console logs.  I can print objects pretty easily for the findOneById but not findAndPullArray  I'm not sure if there's an easier way to check if the data is going into the db itself correctly.

**Comment by monotkate** [comment]
I meant updateOnePullArray

**Comment by monotkate** [comment]
hold up.  Ignore for a bit :D

**Comment by monotkate** [comment]
Alright, unignore me.  As far as I can tell, the new information is making it to updateOneArrayElement correctly.  However, when it refreshes the idea, the information about the owner's back is gone and doesn't update.  This is a backend issue that is over my head at that point, since I don't know how to track what happens to that information and how it may not be inserting correctly into the db.  New backers that are not the idea owner seem to be correctly adding on new ideas, and the demo ideas that were pre-set have no problem with idea owner.  It's just new ideas with an owner editing their backing types.  I'm highly curious as to what's happening though.

**Comment by Mctalian** [comment]
Can you reproduce in production? Try it out and just delete your idea. If
not, something happened within the past week. If so, I'll take a look after
this meeting to see what is going on.

**Comment by monotkate** [comment]
I don't have ldap set up so I never run the prod server.  Let me know if you take a look.

**Comment by Mctalian** [comment]
I meant just visit the actual production server at innovate.ra.rockwell.com,
i'll check it out shortly

**Comment by Mctalian** [comment]
This is present in production, I'll look into what's going on.

**Comment by Mctalian** [comment]
Ok, so here's the issue. When MongoDB creates a document in a collection, it assigns an objectId that looks like this: `566e4681dc6f8f7029385281`

So that's a string form, but apparently in the database it's stored as an object following a particular schema. So when we're trying to search for the back posted by the author, we're looking for authorId === the object _id, not the string. Ideas generated when starting the server were storing the object, but new ideas are storing the string.

So I've got a fix, I'll put up a PR tomorrow once my other one goes through. I will also add a little more in the way of letting the user know when something unexpected happens (a.k.a. the db query for an update returns no results).

**Comment by YashdalfTheGray** [comment]
Yeah, this is what I'm dealing with when I tried to implement the `/ideas/search` route and then test it with any kind of an id. I was hoping that mongo's node client was good enough to recognize that it needed to cast the string passed in as an id before searching for it but it sounds like it's totally not :frowning:

**Comment by monotkate** [comment]
Alright, I'm glad I'm not crazy.  I was so freaking confused.  Once we get this fixed up I can change a bunch of the UI to work for ideas.  I've been shifting the team editing implementation and one of those things is the option to delete back on removal.
