### ISSUE TITLE
IE Add Backs Issue on logout

### ISSUE THREAD

**Issue by alanlgirard** [YashdalfTheGray/flintandsteel#207]
On Internet Explorer, if a user adds a back then logs out the back is not shown on the backs tab.  If the user then logs back in, they are able to add a back as if they didn't add one before.  Once they add the "2nd" back both backs show up.  This works properly on Chrome.

@monotkate @Mctalian can either of you take a look into this since you two have the most interaction with the backing?

**Comment by Mctalian** [comment]
I have not been able to reproduce this.

**Comment by davethenipper** [comment]
From discussion:

Refreshing seems to work: Some sort of weird caching issue?

Or IE isn't getting the updated data from the server in the database?

**Comment by Daviddt17** [comment]
I think I solved the issue. Caching in Angular's $http is enabled in IE, so it was a matter of disabling it in the app config. I just pushed the change to my fork, but I do have an issue with not using dot notation.

I'll go ahead and make a PR. Here's the stack overf... I MEAN MY BRILLIANT SOLUTION TO THIS PROBLEM :)

http://stackoverflow.com/a/19771501

**Comment by davethenipper** [comment]
HAHAHAHAHAHAHAHAHAH, amazing work!!!  I guess I need to go through that
phase 2 backlog sooner rather than later.

**Comment by Mctalian** [comment]
Damn, that's awesome. Good work!

Test it out pretty thoroughly, I'm hoping this doesn't cause any adverse behavior anywhere else but I think it'll be pretty good. Damn IE. I wonder what else we'll run into...

Hardening phase will need to be completed on both Chrome and IE. Might as well go with Firefox too.

**Comment by monotkate** [comment]
nice! :+1:

**Comment by Daviddt17** [comment]
Closed with PR #211
