### ISSUE TITLE
MongoDb may have inherent issues which requires us to consider an alternative

### ISSUE THREAD

**Issue by LongArmMcGee** [YashdalfTheGray/flintandsteel#210]
I stumbled across [this reddit post](https://www.reddit.com/r/programming/comments/3x917f/6848_tb_of_data_is_up_for_grabs_due_to_publicly/cy2yg1t) and found some users discussing the merits of MongoDB. I think we should do a bit of research and consider an alternative in the future.

Links from posts which go into more detail:
https://jira.mongodb.org/browse/SERVER-5944
https://www.quora.com/How-much-credibility-does-the-post-Dont-use-MongoDB-have

**Comment by monotkate** [comment]
I'm seeing a lot of positive thoughts for Postgres

**Comment by Mctalian** [comment]
I'm seeing much of the same. My source was that reddit convo until I look
into it more, was yours a different source?

**Comment by monotkate** [comment]
Nope that's the only place I looked too. Worth looking into more though

**Comment by YashdalfTheGray** [comment]
The other one we could look at is CouchDb or PouchDb since Microsoft has hedged their bets on it and MFT uses it as well. Both those groups have done their research plus it would be fitting given Rockwell's recent mobile strategy. The only issue I have with PostgreSQL is that I actually have to write SQL and I'm not all about it.

**Comment by Mctalian** [comment]
Are we positive about that? That reddit post leads me to believe it can be
document-based, perhaps there's a good node module with a decent connector
that still keeps us away from SQL statements.

Either way, as long as we're ensuring data integrity and have data to back
it, I'm happy enough.

**Comment by YashdalfTheGray** [comment]
Yeah, I'm okay with that. I also like that you can set up a sync between couch/pouch dbs so that each server can run it's own copy of couch/pouch and just sync up to the master when necessary or update data from another server. Setting up sync is pretty damn easy.

**Comment by Mctalian** [comment]
So I remember you looking into pouch/couch in the beginning, what was the
reason for not choosing that again?

**Comment by YashdalfTheGray** [comment]
There was an optional dependency failing which I didn't want to show up in the build. Since that's not an issue anymore (considering our build fails anyway), we should give it a try.

**Comment by Mctalian** [comment]
I saw postgresql come up somewhere and it caused me to take a look around at a few things.

[Companies using MongoDB](https://www.mongodb.com/who-uses-mongodb)
[Companies using PostgreSQL](http://www.postgresql.org/about/users/)
[Companies using PouchDB](http://pouchdb.com/users.html)
[Companies using CouchDB](http://www.couchbase.com/case-studies)

Honestly, it's hard to argue that Mongo is used by a lot of big names. At a glance, I think they have a more impressive user base.

We might just need to work on hardening our implementation of Mongo. Maybe look through some of the open issues that could hurt us and, if needed, add some input checking or something to make sure we are unaffected. #209 is really the *most* important thing, beyond that I think we'll be ok.

**Comment by YashdalfTheGray** [comment]
Damn, I did NOT realize that many people use Mongo but yeah, I think you're right. We should be able to make it work if that many people are using it just okay. Once my PR goes through, we can tag team adding authentication our services layer which the Node server can just check against. 

Once #222 goes through, we can write up a spec on what information to include an `access_token` hash that gets sent in the headers for `GET` and in the body for `DELETE`, `PATCH` and `POST`.

**Comment by YashdalfTheGray** [comment]
@Mctalian, do you think we can close this?

**Comment by Mctalian** [comment]
I'd leave it open as a reminder that we should do a bit of research to
ensure we're covering our asses sufficiently in the future. Thoughts?

**Comment by Mctalian** [comment]
Wait, what is this about access_tokens? Sure we can consider that at some point, but the MongoDB authentication I'm referring to is the ability to keep people from opening up mongo on the command line and sending raw queries to our DB because it isn't hard to find it. It lives on the same server as our site, with the default mongo port and no authentication.

**Comment by YashdalfTheGray** [comment]
Oh I meant you couldn't open up something like curl or wget and send requests to our backend API and get all the data. I hadn't thought of restricting the mongo server access but both are required in my view.

**Comment by Mctalian** [comment]
First step is the actual server then we can look at the other. I agree
though they are both needed.
