### ISSUE TITLE
Breaking Down the Notification/Messaging System

### ISSUE THREAD

**Issue by davethenipper** [YashdalfTheGray/flintandsteel#219]
We have many user stories based around in house messaging and notifications.  I need some help to break the user stories down further, add new content, and scrap what we don't want.

Keep in mind this is Phase 2 work.  Phase 1 is priority.

Previous User Stories:
* Tag a user
* Private Messaging
* Notification System:
    * Notification Icon
    * Subscribe to ideas be notified on changes
    * Be notified when someone interacts with your idea
    * Be notified on Private Message
    * Be notified on tag from another user

New User Stories (Post Discussion):

**Comment by LongArmMcGee** [comment]
I thought we decided to drop private messaging?

**Comment by Mctalian** [comment]
We could drop private messaging because having a clickable link to pull up
a Skype window to that person was possible and easy. So we need a card for
that instead.

**Comment by Mctalian** [comment]
As a user, I need to be able to bring another user into a conversation by tagging them in it.

As a user, I need to be able to message another user through the existing Skype for Business platform.

As a user, I need a method of realizing I have outstanding notifications.

As a user, I need to be able to subscribe to an idea and be notified of any changes.

As an idea author, I need to be notified when someone interacts with my idea.

~~Be notified on Private Message~~ not needed

As a user, I need to be notified when I am tagged in a conversation by another user.

**Comment by Mctalian** [comment]
Is my last comment what you were looking for @davethenipper?

**Comment by davethenipper** [comment]
Yup!  I was just seeing if anyone else had any more ideas.  I'll get these put into user stories this coming week.

**Comment by davethenipper** [comment]
Closed with the above User Stories added.
