### ISSUE TITLE
Hardening Tests

### ISSUE THREAD

**Issue by monotkate** [YashdalfTheGray/flintandsteel#220]
Acceptance Criteria - all test files in the green
- [x] ideasView
- [ ] DialogBackCtrl

Following up on @Mctalian 's work, some of the tests need to be improved.  Working on ideasView at the moment.  It may be slowly because I'm still learning testing, but I want to do it.

**Comment by davethenipper** [comment]
Yeah!  Good idea!  I'll add hardening and testing to the next meeting agenda.

**Comment by Mctalian** [comment]
:+1:

**Comment by YashdalfTheGray** [comment]
IdeasView is probably where 90% of our functionality resides anyway. I think this is a perfect focus. We can work on the rest even if phase 3 if necessary. The cyclomatic complexity for the other controllers is WAY lower than IdeasViewCtrl anyway.

**Comment by monotkate** [comment]
Just an update.  I've been writing tests here and there over break.  I'm not sure how they'll change with some of the PRs that will go through and how I've been tweaking a few things to be better functions, but it's still a large improvement.  I split out the dialog controller for backing to make it both easier to test and to stop clogging the ideas view controller.  I still have to set up testing for that.  Improved navigation tests as well.  Still working on a better way to test the dialog controllers more fully so that we can get some of the tests ratings up higher.

![image](https://cloud.githubusercontent.com/assets/11742296/12091290/f46f3a68-b2c3-11e5-9ae2-291ccefa5565.png)

**Comment by YashdalfTheGray** [comment]
You should close this issue @monotkate!

**Comment by monotkate** [comment]
I'm not sure it's done though. Testing isn't all in the green

**Comment by Mctalian** [comment]
Make sure you take out your logs in the tests as well when you go through
to make things green! Yash found your logs and he flipped a table.

**Comment by Mctalian** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by monotkate** [comment]
How do you test the logs without making them go through?

Tell Yash that I'll flip a table back at him for not making sure the tests are all up to par after his last PR 😜

**Comment by YashdalfTheGray** [comment]
This is not an aggressive retort or anything but this is how I've tested logs in the past.
```javascript
it('logs a status message in the console', function() {
    spyOn(console, 'log').and.callFake(function() { });
    thisFunctionLogs();

    expect(console.log).toHaveBeenCalled();
    // if you want to go above and beyond the call of duty, you can say...
    expect(console.log).toHaveBeenCalledWith(theMessage);
});
```

**Comment by monotkate** [comment]
Oh duh yeah I could do that. I'll do a quick fix and submit a PR for it tomorrow. My bad. Was concentrating on fixing all the other stuff

**Comment by Mctalian** [comment]
I was kidding about him being angry, btw. He only grabbed the table and all
of us shouted "No!" in unison and he snapped out of it.

**Comment by monotkate** [comment]
Haha no I caught that. Although if he had flipped a table I would have wanted to witness

**Comment by YashdalfTheGray** [comment]
None of that happened.  And no, it's all good. It was just a passing comment that came out more aggressively than it should have or was appropriate for something like this.

**Comment by Mctalian** [comment]
@monotkate FYI, in part 2 of Event Tag delivery, I am touching addIdeaView and adding new tests, so if you haven't started hardening tests in that, perhaps I'll just do it since I'm in here already. Avoid the merge.

**Comment by Mctalian** [comment]
Wow, nevermind for now... these promises are a pain in the ass to test.

**Comment by Mctalian** [comment]
Ok, I got the other two things up to green, ideaBack is still untouched. Just to give you a heads up so there's no duplicate work.
