### ISSUE TITLE
New Tutorial Blocks on Homepage don't show help text on IE, Edge, or Firefox

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#231]
On a related note, idea search on the homepage doesn't work for these either.

*Only reason I know this is because I'm not installing Chrome on my Surface Book. Whenever I do this, my fans emit a really high pitched squeal. ONLY when I have Chrome installed. Super weird, but it's annoying enough for me that I'm sticking to Firefox for now. It's not because I'm a browser nazi.*

**Comment by Mctalian** [comment]
@bcbrennecke Did your recent PR fix this?

**Comment by bcbrennecke** [comment]
Yes.  It all works.  It got messed up when we did the massive search and replaces
