### ISSUE TITLE
As a developer I want to refactor IdeasView so that my code is correctly structured

### ISSUE THREAD

**Issue by davethenipper** [YashdalfTheGray/flintandsteel#233]
Acceptance Criteria:
- [ ] To Come

Notes:
IdeasView: Needs some refactoring.  Some things are surface oriented and shouldn’t be in there.  Phase 2, b/c it is not needed, but nice to have.  Split IdeasView into directives, and pass data back and forth.

**Comment by YashdalfTheGray** [comment]
I have pushed back on this in the past. About the only directive in `ideasView` was the edit idea section and it's already being converted into a directive. Directives aren't supposed to be used for containerizing code, they are meant to be reusable components. If we can't reuse something from the page with very little modification, we can't make it a directive.
