### ISSUE TITLE
Comments and Updates able to be submitted blank

### ISSUE THREAD

**Issue by alanlgirard** [YashdalfTheGray/flintandsteel#235]
Need to add more error checking to handle the pristine/dirty states of all form fields to ensure that we only submit valid entries

**Comment by YashdalfTheGray** [comment]
Is this a validation issue or do you think the server can take empty fields?

**Comment by YashdalfTheGray** [comment]
Actually, I'm pretty sure that the server can take empty fields but if  we have some validation, we should be good for now.

**Comment by alanlgirard** [comment]
It's just a validation check. We are limiting characters but since the
field is not required there needs to be a few other validation checks
because the form doesn't have a invalid state until the user enters text.

**Comment by LongArmMcGee** [comment]
Meeting Decision: Make the field required instead.
