### ISSUE TITLE
Idea searching doesn't work on new homepage

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#240]
Somehow this also broke @bcbrennecke

**Comment by bcbrennecke** [comment]
Eh what else is new

**Comment by Mctalian** [comment]
Alrighty, I figured it out.

You are using an old version of the `ideaSvc.getIdeaHeaders` API. It now uses promises, so you need a `then` in there somewhere. Also, the resolve and reject "callbacks" no longer have multiple parameters. It's just one response object with a `data` member. Take a look in `ideaSvc` or look around in sidenav.js

The reason this worked before and stopped working is because of the big back-end delivery.

**Comment by bcbrennecke** [comment]
Interesting, that would explain why my word cloud wasn't working with getIdeaHeaders today either

**Comment by Mctalian** [comment]
So since you removed search functionality from the homepage this is no longer relevant, right @bcbrennecke?

**Comment by bcbrennecke** [comment]
I'm going to close this issue purely on principle since github tweeted at me.
...Oh and I removed search functionality.
