### ISSUE TITLE
ideaView title jank

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#268]
This is unacceptable. 

<img width="440" alt="screen shot 2016-01-29 at 9 53 03 am" src="https://cloud.githubusercontent.com/assets/3102848/12678717/27f0de38-c66e-11e5-99c2-14f1c2a79ab1.png">

(Only) this is acceptable

<img width="399" alt="screen shot 2016-01-29 at 9 54 33 am" src="https://cloud.githubusercontent.com/assets/3102848/12678746/5449929a-c66e-11e5-9c48-47e4c6f8f540.png">

**Comment by monotkate** [comment]
It's worse if you're logged in as the user tbh, because then half the icons go below and half don't.  In reality the updated + icons is too large in that format, so it wraps funky.  Definitely an issue though.

**Comment by monotkate** [comment]
Definitely just clicked the wrong button there, whoops.

**Comment by monotkate** [comment]
I've got this halfway fixed right now, waiting for my PR to go through before finishing it up
