### ISSUE TITLE
Increase number of top ideas on the Side-Nav Bar

### ISSUE THREAD

**Issue by davethenipper** [YashdalfTheGray/flintandsteel#276]
With only 5 top ideas there is wasted white space on the side-nav bar.  We decreased this to 5 because of third party bugs.  Those bugs have since been fixed.

**Comment by bcbrennecke** [comment]
I just increased this to 10 with my latest pull request.

**Comment by bcbrennecke** [comment]
Closing.

**Comment by alanlgirard** [comment]
Closed in PR #278.

@bcbrennecke normally you would close the issue after the PR goes through and reference the PR for traceability
