### ISSUE TITLE
Upon focus, "Type of backing" field could display the canned options.

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#34]
Instead of starting the autocomplete once you've entered a character, we can offer the list of possibilities once they click on the field. Especially if the intended behavior is to have them match one of those canned options exactly. I might type "Leadership" or "Development Skills" and not see anything. Showing the list by default would help with this.

**Comment by Mctalian** [comment]
I have some of this completed but I'm seeing weird behavior when I click on an autocomplete option with no text in the box and it creates a chip, then also has the text in the box. It's weird. This one I can reproduce in the [codepen](http://codepen.io/anon/pen/aOpRNN) but perhaps I have something configured incorrectly.

**Comment by YashdalfTheGray** [comment]
Yeah, try what I said in #33 and see what happens. There should be a way to get ngMaterial to show all the chips when clicked so I don't think we have to hack something together.

**Comment by Mctalian** [comment]
Yeah all you do is add `md-min-length="0"` to the `md-autocomplete` attributes IIRC. I also had to change the `querySearch` function to return all the chips when `query` is empty, instead of an empty array.

All of that is from memory, so above names may not be perfectly correct.

**Comment by YashdalfTheGray** [comment]
Yeah, that sounds like it'll work!

**Comment by YashdalfTheGray** [comment]
Bob, can we close this?

**Comment by Mctalian** [comment]
Eh... it's not really our issue anyway. I don't think so at least. I think it's with angular-material. I have it working-ish on my `chips` branch, but the duplicate backing type issue is still present

**Comment by Mctalian** [comment]
angular-material#2623

**Comment by Mctalian** [comment]
https://github.com/angular/material/issues/2623

**Comment by Mctalian** [comment]
This seems to have been fixed in v0.10.1

Will have to check that out and verify. Most of the chips bugs might be fixed as a result.
