### ISSUE TITLE
Idea refresh listeners don't go away when navigated away from that idea page

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#39]
When you navigate to an idea page, it creates an idea refresh timeout that runs every 750ms. When you leave that page, it should stop calling that listener. 

We can catch the changed page event from ui-router on the `$rootScope` using `$rootScope.$on(eventName, handlerFunction)` and then unassign the setTimeout call.

**Comment by Mctalian** [comment]
That should fix this. Please verify.

**Comment by YashdalfTheGray** [comment]
Verified!
