### ISSUE TITLE
Error thrown during data generation when directory doesn't exist

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#44]
A generic error is thrown during `gulp generate:data` when either of the `datastore\ideas` directories is not present at the time you run the command.

Either output a more helpful error message, or do something to account for that. Perhaps run one of the other gulp commands as a pre-requisite to this command to make sure the directories are created.

**Comment by YashdalfTheGray** [comment]
I have gulp tasks that generate those directories, they're in the gulpfile.

**Comment by Mctalian** [comment]
Yup, I noticed that shortly after. PR #45

**Comment by Mctalian** [comment]
PR #45 was successfully merged, closing issue.
