### ISSUE TITLE
IE Compatibility

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#46]
We don't have to fix it... just so we're all aware.

**Comment by YashdalfTheGray** [comment]
What lapse in judgement caused opening up the website in IE in the first place?

**Comment by Mctalian** [comment]
Update: Since PR #70, there are 2 known issues with IE, the rest have been fixed.
* The home page, all of the columns at the bottom like "Innovate, Collaborate, Achieve" all get mashed into the middle of the screen.
* Each idea page doesn't seem to show the md-tabs of comments and backs.

I firmly believe these can be fixed. I can look into these later.

**Comment by Mctalian** [comment]
The homepage can be "fixed" by removing `center` from `md-content`'s `layout-align` at the top of `homeView.tpl.html`. This makes the Rok-Starter logo super disproportionate, so there's still some work to do to make the homepage work perfectly for IE. (This change may also make the logo disproportionate on Chrome as well, haven't tested)

**Comment by Mctalian** [comment]
As for the tabs: Our exact Idea Page (I pasted the md-content portion into a basic angular app Pen) source code shows up in CodePen in IE... So my leading theory is theme issues, but I'm not entirely sold on that.

**Comment by Mctalian** [comment]
The tabs work fine with version 0.9.4 of angular-material.min.css

I've opened an issue on angular-material.

**Comment by Mctalian** [comment]
Tabs
https://github.com/angular/material/issues/3742
https://github.com/angular/angular.js/issues/12348

**Comment by Mctalian** [comment]
Reopening to keep an eye on the Material Design / Angular Versions to ensure that things are fixed before upgrading to a new Material Design or Angular version
