### ISSUE TITLE
Account page

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#5]

**Comment by YashdalfTheGray** [comment]
var user = {
    username: 'TheMainManDarth',
    password: 'mynameisAnakin',
    name: 'Darth Vader',
    email: 'darth.vader@thesith.com'
};

**Comment by Mctalian** [comment]
Is this issue for a real account page instead of the current dummy?

**Comment by YashdalfTheGray** [comment]
It's an issue for the real account page. It's assigned to Matt right now.

Yash Kulshrestha
yash.kulshrestha@gmail.com
(614)563-1153
