### ISSUE TITLE
E2E Testing

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#51]
Write some E2E Tests using Protractor.

**Comment by Mctalian** [comment]
I'm beginning to change my mind on this. If we restructured some things, we could probably stick to unit tests and possibly just write more with increased scope.

**Comment by YashdalfTheGray** [comment]
I think we need to be careful about our unit tests not becoming integration tests or anything but I think you're right about the e2e shit, I don't think the project's the size where it's impossible to test everything end to end manually. 

Honestly, Angular is divided into two camps right now, the people who don't think they need any e2e tests and then there are the people who are working with protractor evangelizing how great this tool is and everything. I think I'm in the "we don't need e2e testing (conditions apply)" camp.

**Comment by Mctalian** [comment]
Sorry, overloaded testing terms. What I meant was, e2e testing at the UI level may not be best. We can probably write larger Karma/Jasmine based tests that don't stub as many things and that might be sufficient.

I agree that unit testing won't cover everything, but Protractor tests are so fragile because the UI has a tendency to change frequently and those tests will break all the time. I ended up commenting out my UI tests during a UI overhaul and I've been debating even trying to get those working again.

**Comment by Mctalian** [comment]
Closing this, we'll look into it if we need to at a later date. The focus now is load testing, which already has a card in Trello.
