### ISSUE TITLE
After submitting a comment or backing, the text stays in the text field

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#54]
Did this just start happening? Maybe it's a regression issue in angular-material?

**Comment by YashdalfTheGray** [comment]
I fixed this, I had a bug open for it earlier.

**Comment by Mctalian** [comment]
I saw it on the latest, can anyone else reproduce this?

**Comment by Mctalian** [comment]
I forgot I submitted this. Issue #60 contains the solution to this.

**Comment by Mctalian** [comment]
Closing this in favor of #60
