### ISSUE TITLE
Keyword suggestion and browsing

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#6]

**Comment by LongArmMcGee** [comment]
Post Min. Viable Prod. (Final Presentation) we will need to provide a way for users to easily browse through issues. We are imagining a system of keywords which will be provided by the Idea submitter and also keywords suggested our system. I'm hoping we can find an open sourced solution, or maybe a online API to suggest keywords based off of the description provided during idea submission. This could be difficult to find though, these types of services are usually paid for services.

**Comment by Mctalian** [comment]
It might be as simple as providing a `keywords` field during idea creation, storing those in a `keywords` key in each database as an array of values. When we query for `ideaheaders`, it will also return `keywords` in those headers.

I'm using [Defiant.js](https://github.com/hbi99/defiant.js) before and it is *very* fast. We could have a search bar at the top of the "all ideas view" and as the user types, it filters out the results based on the keyword matches. If no matches are found, it could search title, and if no results are found there, it could check authors. Then we can add some parsing behavior so people could type something like `author:McTalian` and it would skip the keyword and title searches.

As for system suggested keywords, I haven't found anything, but I'm assuming we can run something small at the client side that checks for words used multiple times, proper nouns, longer words, etc. and adds them to they keywords field automagically (as chips, even). This would be the harder portion to

**Comment by Mctalian** [comment]
I think we can close this? Our searching right now is definitely MVP. If/when we add tagging we should cover most of our bases.

**Comment by YashdalfTheGray** [comment]
Yeah, I agree.
