### ISSUE TITLE
Side Nav scrolling performance

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#64]
As a result of PR #63, scrolling performance on the sidenav has decreased. I believe this is due to many elements on the DOM. Perhaps we can refactor the idea-item directive and slim it down a bit, or limit the Top Ideas to 5 to eliminate scrolling altogether, though we'll want to look into a "longer term" solution because there will be a day where scrolling is required on the sidenav.

**Comment by Mctalian** [comment]
The next version of angular-material might have virtual repeaters, I've seen it on the latest Docs page. So that might be something that will help this out.

**Comment by Mctalian** [comment]
Issue #65

**Comment by Mctalian** [comment]
It appears this is actually not our issue, so #65 is likely unneeded once this gets patched up:

https://github.com/angular/material/issues/3531
https://github.com/angular/angular.js/issues/12280

**Comment by Mctalian** [comment]
Looks like it's slated for Angular 1.4.4 which is targeted for July 20th but 1.4.3 is already 3 days past due.

**Comment by davethenipper** [comment]
Since we now limit the SideNav, should we close this?

**Comment by Mctalian** [comment]
Potentially. We should look into mobile and wait until we add a few more
links to the sidenav. Or we can close it and reopen a new one of it becomes
an issue again

**Comment by Mctalian** [comment]
I will upgrade to angular 1.4.5 to see if the issue is fixed.

**Comment by Mctalian** [comment]
Upgrading to 1.4.5 does fix the issue if the number of ideas isn't limited to 5. It's actually really nice and smooth now. So someone just needs to officially put the pull request up and it should be good.

**Comment by Mctalian** [comment]
We upgraded to 1.4.7, so this is good.
