### ISSUE TITLE
More than 11 concurrent events will cause a memory leak warning, events may stop working - Increase event limit

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#67]
Node has a default of 11 concurrent events, so we'd have to increase that to something a bit higher for external prototyping and demo-ing.

**Comment by YashdalfTheGray** [comment]
Damnit :-1:

**Comment by Mctalian** [comment]
It's memory leak protection. So it's actually a good thing they have in place. In fact,  it showed me that I had a memory leak during initial attempts. We just need to set an intelligent new limit. For example if we can only support 50 concurrent connections anyway, we can just raise the max to 50 as well for events.

**Comment by Mctalian** [comment]
I'm actually not 100% certain it crashes the server, I actually think it's just a warning. This issue is mainly just to document this and make a decision at some point. We can test further to assess the risk.

**Comment by YashdalfTheGray** [comment]
Ah okay, I thought it would go nuclear at 11 and I was hoping that for at least the prototyping stage, we wouldn't have multi-thread node.

P.S.: Sorry for all the chatter, I'm catching up from the last 2-3 weeks.

**Comment by Mctalian** [comment]
Should be pretty easy to disable if needed. But I just think we need to verify the behavior one time. I'm pretty sure it's just a warning and it's not really multi-threaded.

Actions that users take via the web interface trigger events.

A like or a new Idea will trigger the "ideaHeaders" event which will update everyone's sidenavs. Any client that is listening for that event will receive it and get that update.

A like, a new comment, or a back will trigger the "idea/#" event which will update everyone's ideaView that is browsing that particular idea at that time. So if I post a new comment to the ROK-Starter idea, and you are viewing it, you will see my comment in realtime. But if you're viewing a different idea, you'll be unaffeced because you are not subscribed to the event at that time.

**Comment by Mctalian** [comment]
This just produces a warning, but events might stop working after this warning. I will increase it to 102, so if we have 50 concurrent users consuming 2 events each, it would stil work fine.

**Comment by Mctalian** [comment]
I need to add `require('events').EventEmitter.prototype._maxListeners = 102;` to `server\Ideas.js`

**Comment by Mctalian** [comment]
I've noticed since the DB changes, you can reproduce this warning all the time. Could be something about not closing the DB... the main problem is because we make so many queries to the DB at once, we can't close it. We'll have to think about this.

**Comment by Mctalian** [comment]
I think I may have fixed the above comment using connection pooling:

http://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html
