### ISSUE TITLE
LDAP/AD Authentication

### ISSUE THREAD

**Issue by Mctalian** [YashdalfTheGray/flintandsteel#72]
Just a placeholder for now so I can put some research here as I find it.

http://stackoverflow.com/questions/21439030/passport-active-directory-node-js
https://www.npmjs.com/package/passport-ldapauth
http://stackoverflow.com/questions/29121502/nodejs-passport-passport-ldap-connectionerror-ldaps-ldap-xxxx-com636-close?rq=1
http://stackoverflow.com/questions/25171613/ldap-bind-error-using-node-js-and-ldapjs (Particularly the last comment)

**Comment by davethenipper** [comment]
There is a user story on Trello for this.  Possibly move the links to Trello and close this?
