### ISSUE TITLE
Using RequireJS to do dynamic loading?

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#75]
http://requirejs.org/

I'm using something like this in an Angular2 app and I think we can use it to load things as required and further decrease our initial load times.

Any thoughts?

**Comment by Mctalian** [comment]
I have seen it referenced a lot but have never used it myself. The way I handled this on my project was minifying, caching, deferring js to the bottom, cloudflare, etc. So maybe this is a better way for us. I don't really have any first-hand experience though.

**Comment by YashdalfTheGray** [comment]
So I'm using systemjs in another project and although it's only got like two files to load (so I can't tell the performance benefits), it already is leading to cleaner code. 

On the other hand, minifying and moving the scripts to the bottom should lead to a good enough performance increase that we won't need something like requirejs or systemjs.

I know you mentioned it in one of the meetings that we had about optimizing and I wanted to get your view on it.

**Comment by YashdalfTheGray** [comment]
Closing this, this'll probably be a discussion for the future.
