### ISSUE TITLE
Change the contributing section

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#79]
I think we should lay out the new rules for contributing and we should do it in the github fashion of creating a CONTRIBUTING.md file. What do you guys think? I can get a draft started.

**Comment by Mctalian** [comment]
Sounds good to me

**Comment by YashdalfTheGray** [comment]
Sweet. Starting a rough draft.

**Comment by YashdalfTheGray** [comment]
Merged, closing issue
