### ISSUE TITLE
Using spaces instead of tabs

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#88]
We need to start using 4 spaces instead of tabs for flintandsteel. The code layout on github is getting slightly ridiculous. It's pretty easy to switch, someone just needs to go back and make all the existing files use spaces instead of tabs too. I can get on that but we're going to have to code freeze for a couple of days this weekend or something. 

Thoughts? @Mctalian @davethenipper @bcbrennecke @LongArmMcGee

**Comment by Mctalian** [comment]
I agree. It's pretty annoying.

**Comment by davethenipper** [comment]
Uniformity would be nice. I'm fine with a code freeze.

**Comment by YashdalfTheGray** [comment]
Okay, so let's plan for a code freeze starting on Sunday and it'll last through Monday night just in case I can't get to all of the files. Should I create a PR for it or change master? What do you guys think?

**Comment by YashdalfTheGray** [comment]
Just checked it all in.
