### ISSUE TITLE
What about a coding standard?

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#91]

**Comment by bcbrennecke** [comment]
Are you suggesting we decide on one?

**Comment by YashdalfTheGray** [comment]
I was thinking more along the lines of implementing one. There are pretty good coding standards already out there for Javascript so we shouldn't need to reinvent the wheel here. 

That being said, once we put one in and we think that a part of the standard is crap, we can remove it.

**Comment by bcbrennecke** [comment]
I think it's probably a good idea to have some sort of standard.  Let's talk about it in the meeting this week.

**Comment by YashdalfTheGray** [comment]
Done and done e64d47fd1aafecc0ab6c9a55a7d4870755e37a0f
