### ISSUE TITLE
Installing mongo's native driver on Windows

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/flintandsteel#94]
@Mctalian have you ever seen this? I'm on Windows 10 with Python and Visual Studio 2015. 

I did some research and I'm seeing a couple of things,
* You need to have Python and Visual Studio (recommended) or Visual C++ (bare minimum) installed
* Kerberos is not required for mongo's node driver to work so I'm willing to make it ride
* It totally, without issue, worked on my work computer, Windows 7, only python installed.
* `node-gyp` is a total mess on Windows and we should think about updating to Node 4.1.1 and see if that works 
* npm closed the [issue](https://github.com/npm/npm/issues/5399) that someone posted which gave me the upgrading to node idea

I'm confuzzled. Thoughts?

```console
  kerberos_sspi.c
LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' [c:\Users\Yash Kulsh
restha\git-yash\flintandsteel\node_modules\mongodb\node_modules\mongodb-core\no
de_modules\kerberos\build\kerberos.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\Yash Kulshrestha\git-yash\flintandsteel\node_modules\mongodb\node_modules\mongodb-core\node_modules\kerberos
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
mongodb@2.0.45 node_modules\mongodb
├── es6-promise@2.1.1
├── readable-stream@1.0.31 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── mongodb-core@1.2.14 (bson@0.4.12, kerberos@0.0.14)
```

**Comment by Mctalian** [comment]
Have you tried upgrading node yet?

**Comment by YashdalfTheGray** [comment]
I have not. If upgrading node solves the issue then I think we should upgrade all of our project to the latest version of Node and make sure everyone has that version.

**Comment by YashdalfTheGray** [comment]
Travis just got support for Node 4.1 so we can make sure everyone is up to that version and also be able to test against that.

**Comment by Mctalian** [comment]
Test it locally, if it works, then we'll update everyone.

**Comment by YashdalfTheGray** [comment]
Mongo is working fine independent of the error. I'm closing this, will open if there is more of an issue.
